[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/link/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev:all"
  port = 8888
  targetPort = 5173
  publish = "dist"